### ISSUE TITLE
frequency_far_jump not work

### ISSUE THREAD

**Issue by Jinvis** [0xAF/openwebrxplus-plugins#10]
Hi, I tried to use pligin frequency_far_jump, it run well, but nothing happend after
 ws.send(JSON.stringify({
          "type": "setfrequency", "params": { "frequency": f, "key": k }
        }));
Can you help to check it? 

Thanks.
![Capture](https://github.com/user-attachments/assets/6921e171-08a8-4058-b901-2bbe1bcf4350)

**Comment by 0xAF** [comment]
@LZ2DMV Care to check this?

**Comment by 0xAF** [comment]
@Jinvis I see 2 things you can try to confirm if it's broken.
1. your magic key seems to be with utf8 chars, try with latin characters only and see if this helps
2. the plugin seems to be installed locally, are you sure it is not modified? you can try to load it remotely.

If @LZ2DMV have no time to inspect this, I will check it later.

**Comment by LZ2DMV** [comment]
@Jinvis Could you please share your entire console output or attach it as a text file here?

**Comment by Jinvis** [comment]
Hi,
I run openwebrxplus in docker, this is my setting and logs:
![image](https://github.com/user-attachments/assets/24af4730-0349-4ca8-841b-df5432ef263e)
![image](https://github.com/user-attachments/assets/8fbc6a8b-7fa1-4115-a806-a19ccef15e5b)
![image](https://github.com/user-attachments/assets/30d358cd-9431-4408-90a2-e52f3026422b)

**Comment by Jinvis** [comment]
Hi @LZ2DMV 
I can't find any useful log both in docker console and web console, is there any other debug flag for this issue?

Thanks.

**Comment by Jinvis** [comment]
> @Jinvis I see 2 things you can try to confirm if it's broken.
> 
> 1. your magic key seems to be with utf8 chars, try with latin characters only and see if this helps
>    EDIT: as it seems they just looked as UTF8 to me, but they are not.. so ignore this point.
> 2. the plugin seems to be installed locally, are you sure it is not modified? you can try to load it remotely.
> 
> If @LZ2DMV have no time to inspect this, I will check it later.

1. I tried to change  magic_key to xiaowei with "_", issue still exist.
2. the plugin file is form github, I only modified init.js.

**Comment by 0xAF** [comment]
>     2. the plugin file is form github, I only modified init.js.

Can you try to change this line in your `init.js`:
```
Plugins.load('frequency_far_jump');
```

with this line:
```
Plugins.load(rp_url + 'frequency_far_jump/frequency_far_jump.js');
```

This way the plugin will be loaded remotely, instead of your local plugin.
Just in case you have a problem with the local plugin.

**Comment by 0xAF** [comment]
Please also check if the plugin actually works, because from the error in your web console, it seems that you tried to change the frequency, before the WebSocket is fully established. I don't know how you do that, but my guess is that you can ignore this error and still be able to use the plugin without problems later.

**Comment by Jinvis** [comment]
Hi @0xAF ,
Because the network issue, I can't always access github, so I used local file replace network file, I double check all files, they loaded well, and it can run into Plugins.utils.wrap_func/ send data, but nothing happend after that, if there any way to get more detail debug info?
![image](https://github.com/user-attachments/assets/f1b259d1-f91c-4406-b2ad-931237659b60)

**Comment by 0xAF** [comment]
Your WebSocket is still in "CONNECTING" state. This is not normal. The plugin can be made to check if this is the case and wait until the WebSocket is CONNECTED, before sending the command to the server, but this will not fix your problem IMO. I will wait for @LZ2DMV to comment.

**Comment by Jinvis** [comment]
By the way, the example theme in plugin folder works well.

![image](https://github.com/user-attachments/assets/04e6ca56-f8fa-4f3b-9b22-81088bfd7023)

**Comment by LZ2DMV** [comment]
@Jinvis As far as i am concerned, this appears to be some kind of a network issue on your side - something is messing up with your websockets. The plugin is dead simple and there's not much to go wrong with it. Just to be sure, we tested it on the last OWRXP release last night and it is working without any problems.

If this is in your local network, is there some HIDS/HIPS on your network/computer that could block WS?

Also, i asked about your browser's web console output, not your Docker container logs.

**Comment by Jinvis** [comment]
@LZ2DMV  I agree with you, maybe something block the websocket in host pc, I will try to find the root cause, just close this issue, it is  not from plugin tool.

Thanks.

**Comment by 0xAF** [comment]
You might want to try with another browser and/or device (or may be in Private/Incognito mode). Just to be sure it is not some browser addon/extension.
